=== mikekchar/brewfar/beer.dtd
<!ELEMENT beer (name, style, first-brewed, brewers, ingredients, stats, log, notes)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT style (#PCDATA)>
<!ELEMENT first-brewed (#PCDATA)>
<!ELEMENT brewers (#PCDATA)>
<!ELEMENT ingredients (fermentables,flavourings,yeast+,priming)>
<!ELEMENT fermentables (malt*)>
<!ELEMENT malt (type, qty, added)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT qty (#PCDATA)>
<!ATTLIST qty
          units CDATA #REQUIRED>
<!ELEMENT added (#PCDATA)>
<!ELEMENT flavourings (hop*)>
<!ELEMENT hop (type,acid,qty,added)>
<!ELEMENT acid (#PCDATA)>
<!ELEMENT yeast (type,qty,added)>
<!ELEMENT priming (type,qty)>
<!ELEMENT stats (sg,fg,attenuation,extract,colour,ibu)>
<!ELEMENT sg (#PCDATA)>
<!ELEMENT fg (#PCDATA)>
<!ELEMENT attenuation (#PCDATA)>
<!ELEMENT extract (#PCDATA)>
<!ELEMENT colour (#PCDATA)>
<!ELEMENT ibu (#PCDATA)>
<!ELEMENT log (summary,action*)>
<!ELEMENT summary (type,mashin?,protein?,sacharification?,mashout?,sparge?,preboil?,boil?,chill?,primary?,secondary?)>
<!ELEMENT mashin (temp,thickness)>
<!ELEMENT thickness (#PCDATA)>
<!ATTLIST thickness
          units CDATA #REQUIRED>
<!ELEMENT time (#PCDATA)>
<!ELEMENT protein (temp,time)>
<!ELEMENT sacharification (temp,time)>
<!ELEMENT mashout (temp,time)>
<!ELEMENT sparge (temp,time)>
<!ELEMENT preboil (time)>
<!ELEMENT boil (time)>
<!ELEMENT chill (time)>
<!ELEMENT primary (temp?,time)>
<!ELEMENT secondary (temp?,time)>
<!ELEMENT action (time,temp?,desc?)>
<!ELEMENT temp (#PCDATA)>
<!ATTLIST temp
          units CDATA #REQUIRED>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT notes (#PCDATA)>

=== mikekchar/brewfar/Trilobyte.xml
<?xml version="1.0" standalone="no" ?>
<?xml-stylesheet type="text/xsl" href="brewfar1.xsl" ?>
<!DOCTYPE beer PUBLIC "-//MKC/Beer 0.01//EN" "http://rook.dyndns.org/pub-beer/beer.dtd">
<beer>
  <name>Trilobyte Brown</name>
  <style>American Brown Ale</style>
  <first-brewed>June 15, 2003</first-brewed>
  <brewers>Mike, Nick and Don</brewers>
  <ingredients>
    <fermentables>
       <malt>
          <type>Pale 2-Row (Canadian)</type>
          <qty units="kg">4.00</qty>
          <added>mash</added>
       </malt>
       <malt>
         <type>Crystal</type>
         <qty units="kg">0.50</qty>
          <added>mash</added>
       </malt>
       <malt>
         <type>Chocolate</type>
         <qty units="kg">0.25</qty>
          <added>mash</added>
       </malt>
    </fermentables>
    <flavourings>
      <hop>
        <type>Northern Brewer</type>
        <acid>6.3</acid>
        <qty units="g">50</qty>
        <added>60 min</added>
      </hop>
      <hop>
        <type>Cascade</type>
        <acid>5.4</acid>
        <qty units="g">12</qty>
        <added>15 min</added>
      </hop>
    </flavourings>
    <yeast>
      <type>British Ale (Wyeast 1098)</type>
      <qty units="smackpack">1</qty>
      <added>Primary</added>
    </yeast>
    <priming>
      <type>Dextrose</type>
      <qty units="cup">0.5</qty>
    </priming>
  </ingredients>
  <stats>
    <sg>1040</sg>
    <fg>1011</fg>
    <attenuation>72.5%</attenuation>
    <extract>64%</extract>
    <colour>45.5</colour>
    <ibu>39.2</ibu>
  </stats>
  <log>
    <summary>
      <type>Step Controlled Mash</type>
      <mashin>
        <temp units="C">18</temp>
        <thickness units="l/kg">2.53</thickness> 
      </mashin>
      <protein>
        <temp units="C">56</temp>
        <time>30 min</time>
      </protein>
      <sacharification>
        <temp units="C">66</temp>
        <time>53 min</time>
      </sacharification>
      <mashout>
        <temp units="C">80</temp>
        <time>15 min</time>
      </mashout>
      <sparge>
        <time>30 min</time>        
      </sparge>
      <preboil>
        <time>52 min</time>        
      </preboil>
      <boil>
        <time>97 min</time>
      </boil>
      <chill>
        <time>37 min</time>
      </chill>
      <primary>
        <time>7 days</time>
      </primary>
      <secondary>
        <time>7 days</time>
      </secondary>
    </summary>
    <action>
      <time>3:37</time>
      <temp units="C">18</temp>
      <desc>Dough in 12 liters (heat on)</desc>
    </action>
    <action>
      <time>4:14</time>
      <temp units="C">55</temp>
      <desc>Start Protein Rest (heat off)</desc>
    </action>
    <action>
      <time>4:44</time>
      <temp units="C">56</temp>
      <desc>End Protein Rest (heat on)</desc>
    </action>
    <action>
      <time>4:58</time>
      <temp units="C">66</temp>
      <desc>Start Sacharification Rest (heat off)</desc>
    </action>
    <action>
      <time>5:51</time>
      <temp units="C">65</temp>
      <desc>End Sacharification Rest (heat on)</desc>
    </action>
    <action>
      <time>6:23</time>
      <temp units="C">80</temp>
      <desc>Start Mash Out (heat off)</desc>
    </action>
    <action>
      <time>6:38</time>
      <desc>Start Sparge (recirculate 6 liters)</desc>
    </action>
    <action>
      <time>7:08</time>
      <desc>End Sparge (heat on)</desc>
    </action>
    <action>
      <time>8:00</time>
      <temp units="C">100</temp>
      <desc>At a boil</desc>
    </action>
    <action>
      <time>8:30</time>
      <temp units="C">100</temp>
      <desc>Add first hop addition</desc>
    </action>
    <action>
      <time>9:16</time>
      <temp units="C">100</temp>
      <desc>Add second hop addition</desc>
    </action>
    <action>
      <time>9:37</time>
      <temp units="C">100</temp>
      <desc>Start chiller</desc>
    </action>
    <action>
      <time>10:14</time>
      <temp units="C">19</temp>
      <desc>Chill Finished</desc>
    </action>
    <action>
      <time>10:22</time>
      <desc>Top up and pitch yeast. SG 1040</desc>
    </action>
    <action>
      <time>Day 1</time>
      <desc>Rack - Krausen just starting</desc>
    </action>
    <action>
      <time>Day 7</time>
      <desc>Rack - Krausen done, cloudy.  Tastes good.</desc>
    </action>
    <action>
      <time>Day 14</time>
      <desc>Clear. FG 1011. Bottle 0.5 cups dextrose priming</desc>
    </action>
  </log>
  <notes>
    <p>
    Can't really remember much about this beer.  Didn't write any
    notes down about it.  I remember it was fairly tasty.  We drank
    it quite quickly, so it must have been good.
    </p>
  </notes>
</beer>

=== mikekchar/brewfar/JackiesTipple.xml
<?xml version="1.0" standalone="no" ?>
<?xml-stylesheet type="text/xsl" href="brewfar1.xsl" ?>
<!DOCTYPE beer SYSTEM "beer.dtd">
<beer>
  <name>Jackie's Tipple</name>
  <style>Scottish Export</style>
  <first-brewed>September 19, 2004</first-brewed>
  <brewers>Mike and Suds</brewers>
  <ingredients>
	<fermentables>
	  <malt>
		<type>Fawcett Marris Otter</type>
		<qty units="kg">4.8</qty>
		<added>mash</added>
	  </malt>
	  <malt>
		<type>Roast Barley</type>
		<qty units="g">30</qty>
		<added>Mash</added>
	  </malt>
	</fermentables>
	<flavourings>
	  <hop>
		<type>Goldings (American pellets)</type>
		<acid>4.75</acid>
		<qty units="g">28</qty>
		<added>60</added>
	  </hop>
	  <hop>
		<type>Norther Brewer (German plugs)</type>
		<acid>7.4</acid>
		<qty units="g">14</qty>
		<added>20</added>
	  </hop>
	</flavourings>
	<yeast>
	  <type>Cooper's Gold Foil</type>
	  <qty units="packages">2</qty>
	  <added>TBD</added>
	</yeast>
	<priming>
	  <type>TBD</type>
	  <qty units="cups">TBD</qty>
	</priming>
  </ingredients>
  <stats>
	<sg>1.054</sg>
	<fg>1.015</fg>
	<attenuation>72</attenuation>
	<extract>80</extract>
	<colour>10.8</colour>
	<ibu>24.3</ibu>
  </stats>
  <log>
	<summary>
	  <type>Infusion Mash</type>
	  <mashin>
		<temp units="C">70</temp>
		<thickness units="l/kg">2.7</thickness>
	  </mashin>
	  <sacharification>
		<temp units="C">70</temp>
		<time>60 min</time>
	  </sacharification>
	  <mashout>
		<temp units="C">75</temp>
		<time>15</time>
	  </mashout>
	</summary>
	<action>
	  <time>0:00</time>
	  <temp units="C">170</temp>
	  <desc>Infuse with 13.04 L @ 77.4 C</desc>
	</action>
	<action>
	  <time>1:00</time>
	  <temp units="C">175</temp>
	  <desc>Infuse with 3 L @ Boiling</desc>
	</action>
	<action>
	  <time>1:15</time>
	  <desc>Sparge with 12.31 L @ 75 C</desc>
	</action>
	<action>
	  <time>1:30</time>
	  <desc>Caramalize 4 L of first runnings</desc>
	</action>
	<action>
	  <time>2:30</time>
	  <desc>Boil.  Adjust wort to SG 47.6 @ 60 C</desc>
	</action>
  </log>
  <notes></notes>
</beer>

=== mikekchar/brewfar/MonsterMash.xml
<?xml version="1.0" standalone="no" ?>
<?xml-stylesheet type="text/xsl" href="brewfar1.xsl" ?>
<!DOCTYPE beer SYSTEM "beer.dtd">
<beer>
  <name>Monster Mash Pale Ale</name>
  <style>Pale Ale</style>
  <first-brewed>July 6, 2003</first-brewed>
  <brewers>Mike and Nick</brewers>
  <ingredients>
	<fermentables>
	  <malt>
		<type>2 row Pale Ale malt</type>
		<qty units="kg">4.5</qty>
		<added>mash</added>
	  </malt>
	  <malt>
		<type>Munich malt</type>
		<qty units="kg">0.5</qty>
		<added>mash</added>
	  </malt>
	</fermentables>
	<flavourings>
	  <hop>
		<type>Saaz</type>
		<acid>3.6</acid>
		<qty units="g">50</qty>
		<added>Mash Hop</added>
	  </hop>
	  <hop>
		<type>Saaz</type>
		<acid>3.6</acid>
		<qty units="g">70</qty>
		<added>First Wort Hop</added>
	  </hop>
	</flavourings>
	<yeast>
	  <type>WYeast 1098</type>
	  <qty units="Yeast Cake"></qty>
	  <added>Primary</added>
	</yeast>
	<priming>
	  <type>Dextrose</type>
	  <qty units="cup">Unknown (probably 0.66)</qty>
	</priming>
  </ingredients>
  <stats>
	<sg>48</sg>
	<fg>8</fg>
	<attenuation>83%</attenuation>
	<extract>77%</extract>
	<colour>4.7</colour>
	<ibu>32.3</ibu>
  </stats>
  <log>
	<summary>
	  <type>Step Controlled Mash</type>
	  <mashin>
		<temp units="C">21</temp>
		<thickness units="2.8"></thickness>
	  </mashin>
	  <protein>
		<temp units="C">58</temp>
		<time>30 min</time>
	  </protein>
	  <sacharification>
		<temp units="65">89 min</temp>
		<time></time>
	  </sacharification>
	  <mashout>
		<temp units="C">90</temp>
		<time>22 min</time>
	  </mashout>
	  <sparge>
		<temp units="C">76</temp>
		<time>23 min</time>
	  </sparge>
	  <preboil>
		<time>51 min</time>
	  </preboil>
	  <boil>
		<time>61 min</time>
	  </boil>
	  <chill>
		<time>30 min</time>
	  </chill>
	  <primary>
		<time>7 days</time>
	  </primary>
	  <secondary>
		<time>7 days</time>
	  </secondary>
	</summary>
	<action>
	  <time>2:21</time>
	  <temp units="C">21</temp>
	  <desc>Dough in 14L</desc>
	</action>
	<action>
	  <time>2:59</time>
	  <temp units="C">56</temp>
	  <desc>Heat off</desc>
	</action>
	<action>
	  <time>3:29</time>
	  <temp units="C">58</temp>
	  <desc>Heat on</desc>
	</action>
	<action>
	  <time>3:40</time>
	  <temp units="C">65</temp>
	  <desc>Heat off</desc>
	</action>
	<action>
	  <time>4:54</time>
	  <temp units="C">64</temp>
	  <desc>Heat on</desc>
	</action>
	<action>
	  <time>5:23</time>
	  <temp units="C">90</temp>
	  <desc>Heat off</desc>
	</action>
	<action>
	  <time>5:45</time>
	  <temp units="C">76</temp>
	  <desc>Start Sparge -- recirculate 6 liters</desc>
	</action>
	<action>
	  <time>6:08</time>
	  <temp units="C">66</temp>
	  <desc>End Sparge</desc>
	</action>
	<action>
	  <time>6:59</time>
	  <desc>Boil Start</desc>
	</action>
	<action>
	  <time>8:00</time>
	  <desc>Boil End</desc>
	</action>
	<action>
	  <time>8:30</time>
	  <temp units="C">20</temp>
	  <desc>Chill end</desc>
	</action>
	<action>
	  <time>9:05</time>
	  <desc>Done</desc>
	</action>
	<action>
	  <time>Day 7</time>
	  <desc>Racked</desc>
	</action>
  </log>
  <notes>
  This was the big experiment with mash hopping and first wort
  hopping.  Our conclusion was that FWH was useful from at least
  a convenience point of view and that mash hopping didn't work
  for us at all.  There is *no* saaz character to this beer.
  For all that, it's a nice beer.  One or two of the bottles got
  infected.  The yeast is all wrong for this beer, and the hops
  don't come out at all.  I wouldn't do this one again.  BTW, notice
  that our subsequent repitchings of 1098 are resulting in higher
  attenuation.
  </notes>
</beer>

=== mikekchar/brewfar/OttawaPride.xml
<?xml version="1.0" standalone="no" ?>
<?xml-stylesheet type="text/xsl" href="brewfar1.xsl" ?>
<!DOCTYPE beer SYSTEM "beer.dtd">
<beer>
  <name>Ottawa Pride</name>
  <style>English Pale Ale</style>
  <first-brewed>July 13, 2003</first-brewed>
  <brewers>Mike and Nick</brewers>
  <ingredients>
	<fermentables>
	  <malt>
		<type>6 Row Pale Ale</type>
		<qty units="kg">4.0</qty>
		<added></added>
	  </malt>
	  <malt>
		<type>Crystal Malt</type>
		<qty units="kg">0.25</qty>
		<added></added>
	  </malt>
	</fermentables>
	<flavourings>
	  <hop>
		<type>Fuggles</type>
		<acid>4.9%</acid>
		<qty units="g">25</qty>
		<added>FWH</added>
	  </hop>
	  <hop>
		<type>Goldings</type>
		<acid>5.0%</acid>
		<qty units="g">30</qty>
		<added>FWH</added>
	  </hop>
	  <hop>
		<type>Goldings</type>
		<acid>5.0%</acid>
		<qty units="g">10</qty>
		<added>15</added>
	  </hop>
	</flavourings>
	<yeast>
	  <type>WYeast 1098 British Ale Yeast</type>
	  <qty units="Yeast Cake">1</qty>
	  <added>Primary</added>
	</yeast>
	<priming>
	  <type>Dextrose</type>
	  <qty units="cup">Unknown (~0.6 cups)</qty>
	</priming>
  </ingredients>
  <stats>
	<sg>40</sg>
	<fg>10</fg>
	<attenuation>75.0%</attenuation>
	<extract>80.0%</extract>
	<colour>8</colour>
	<ibu>34.8%</ibu>
  </stats>
  <log>
	<summary>
	  <type>Infusion Mash</type>
	  <mashin>
		<temp units="C">67</temp>
		<thickness units="l/kg">2.4</thickness>
	  </mashin>
	  <sacharification>
		<temp units="C">66</temp>
		<time>97 min</time>
	  </sacharification>
	  <mashout>
		<temp units="C">75</temp>
		<time>15</time>
	  </mashout>
	  <sparge>
		<temp units="C">65</temp>
		<time>15 min</time>
	  </sparge>
	  <preboil>
		<time>58 min</time>
	  </preboil>
	  <boil>
		<time>90 min</time>
	  </boil>
	  <chill>
		<time>28 min</time>
	  </chill>
	</summary>
	<action>
	  <time>2:27</time>
	  <temp units="C">67</temp>
	  <desc>Mashin with 8.5L of 83 degree water</desc>
	</action>
	<action>
	  <time>3:30</time>
	  <temp units="C">64</temp>
	  <desc>1.5L infusion to get to 67 degrees</desc>
	</action>
	<action>
	  <time>4:05</time>
	  <temp units="C">75</temp>
	  <desc>Infuse 8L</desc>
	</action>
	<action>
	  <time>4:20</time>
	  <desc>Start recirculation</desc>
	</action>
	<action>
	  <time>4:35</time>
	  <temp units="C">65</temp>
	  <desc>End sparge</desc>
	</action>
	<action>
	  <time>5:33</time>
	  <desc>Boil</desc>
	</action>
	<action>
	  <time>6:55</time>
	  <desc>Add rest of hops</desc>
	</action>
	<action>
	  <time>7:03</time>
	  <desc>Boil Done</desc>
	</action>
	<action>
	  <time>7:07</time>
	  <desc>Start chill</desc>
	</action>
	<action>
	  <time>7:35</time>
	  <temp units="C">23</temp>
	  <desc>Chill finished</desc>
	</action>
	<action>
	  <time>7:47</time>
	  <desc>Done brewing</desc>
	</action>	
	<action>
	  <time>Aug 16</time>
	  <desc>Bottle</desc>
	</action>	
  </log>
  <notes>
  <p>
  This beer is inspired by Fuller's London Pride.  It's by no means
  a clone (in fact it tastes very different).  But it's a very
  pleasant pale ale.  The first thing that's noticable is that
  the character of the Fuggles and Goldings hops comes through
  nicely.  It's got a nice bitterness to it.  If it's missing
  anything it's on the malt side.  I think a different yeast
  would be needed to improve things.  However, this is a very
  pleasant beer.  Can drink a lot of these.
  </p>
  </notes>
</beer>

=== mikekchar/brewfar/Charlton.xml
<?xml version="1.0" standalone="no" ?>
<?xml-stylesheet type="text/xsl" href="brewfar1.xsl" ?>
<!DOCTYPE beer SYSTEM "beer.dtd">
<beer>
  <name>Charlton's Bitter</name>
  <style>Ordinary Bitter</style>
  <first-brewed>July 23, 2004</first-brewed>
  <brewers>Mike</brewers>
  <ingredients>
	<fermentables>
	  <malt>
		<type>Fawcett Maris Otter Pale Ale</type>
		<qty units="kg">2.7</qty>
		<added>mash</added>
	  </malt>
	  <malt>
		<type>Wyermann Dark Munich</type>
		<qty units="kg">0.3</qty>
		<added>mash</added>
	  </malt>
	  <malt>
		<type>Hugh Baird Wheat Malt</type>
		<qty units="kg">0.3</qty>
		<added>mash</added>
	  </malt>
	  <malt>
		<type>Fawcett Dark Crystal</type>
		<qty units="kg">0.2</qty>
		<added>mash</added>
	  </malt>
	</fermentables>
	<flavourings>
	  <hop>
		<type>Goldings (American)</type>
		<acid>4.25%</acid>
		<qty units="g">40</qty>
		<added>60 min</added>
	  </hop>
	  <hop>
		<type>EKG</type>
		<acid>5.9%</acid>
		<qty units="g">10</qty>
		<added>30 min</added>
	  </hop>
	  <hop>
		<type>EKG</type>
		<acid>5.9%</acid>
		<qty units="g">10</qty>
		<added>15 min</added>
	  </hop>
	  <hop>
		<type>EKG</type>
		<acid>5.9%</acid>
		<qty units="g">10</qty>
		<added>0 min</added>
	  </hop>
	</flavourings>
	<yeast>
	  <type>S-04</type>
	  <qty units="g">12g</qty>
	  <added>primary</added>
	</yeast>
	<priming>
	  <type>TBD</type>
	  <qty units="cup">TBD</qty>
	</priming>
  </ingredients>
  <stats>
	<sg>35</sg>
	<fg>(est) 9</fg>
	<attenuation>75%</attenuation>
	<extract>75%</extract>
	<colour>9.3</colour>
	<ibu>31.2</ibu>
  </stats>
  <log>
	<summary>
	  <type>Infusion Mash</type>
	  <mashin>
		<temp units="C">70</temp>
		<thickness units="l/kg">2.7</thickness>
	  </mashin>
	  <sacharification>
		<temp units="C">70</temp>
		<time>60 min</time>
	  </sacharification>
	  <mashout>
		<temp units="C">75</temp>
		<time>15</time>
	  </mashout>
	</summary>
	<action>
	  <time>0:00</time>
	  <temp units="C">170</temp>
	  <desc>Infuse with 9.45 L @ 77.4 C</desc>
	</action>
	<action>
	  <time>1:00</time>
	  <temp units="C">175</temp>
	  <desc>Infuse with 2.17 L @ Boiling</desc>
	</action>
  </log>
  <notes></notes>
</beer>

=== mikekchar/brewfar/BodySnatcher.xml
<?xml version="1.0" standalone="no" ?>
<?xml-stylesheet type="text/xsl" href="brewfar1.xsl" ?>
<!DOCTYPE beer SYSTEM "beer.dtd">
<beer>
  <name>Body Snatcher</name>
  <style>Pale Ale</style>
  <first-brewed>June 22, 2003</first-brewed>
  <brewers>Mike, Nick, Don</brewers>
  <ingredients>
	<fermentables>
	  <malt>
		<type>2 Row Pale Ale (Canadian)</type>
		<qty units="kg">4.75</qty>
		<added>mash</added>
	  </malt>
	  <malt>
		<type>Crystal Malt</type>
		<qty units="kg">0.13</qty>
		<added>mash</added>
	  </malt>
	</fermentables>
	<flavourings>
	  <hop>
		<type>Goldings (American) pellets</type>
		<acid>4.75</acid>
		<qty units="g">30</qty>
		<added>60 min</added>
	  </hop>
	  <hop>
		<type>Fuggles (American) pellets</type>
		<acid>5.0</acid>
		<qty units="g">15</qty>
		<added>60 min</added>
	  </hop>
	  <hop>
		<type>Goldings (American) pellet</type>
		<acid>4.75</acid>
		<qty units="g">15</qty>
		<added>15</added>
	  </hop>
	  <hop>
		<type>Fuggles (American) pellets</type>
		<acid>5.0</acid>
		<qty units="g">8</qty>
		<added>15 min</added>
	  </hop>
	</flavourings>
	<yeast>
	  <type>WYeast 1098 British Ale Yeast</type>
	  <qty units="yeast cake"></qty>
	  <added></added>
	</yeast>
	<priming>
	  <type>Dextrose</type>
	  <qty units="cup">0.66</qty>
	</priming>
  </ingredients>
  <stats>
	<sg>42</sg>
	<fg>11</fg>
	<attenuation>73.8%</attenuation>
	<extract>68%</extract>
	<colour>5.9</colour>
	<ibu>28.7</ibu>
  </stats>
  <log>
	<summary>
	  <type>Step Infusion Mash</type>
	  <mashin>
		<temp units="C">18</temp>
		<thickness units="kg/l">2.25</thickness>
	  </mashin>
	  <protein>
		<temp units="C">57</temp>
		<time>30 min</time>
	  </protein>
	  <sacharification>
		<temp units="C">66</temp>
		<time>60 min</time>
	  </sacharification>
	  <mashout>
		<temp units="C">80</temp>
		<time>24 min</time>
	  </mashout>
	  <sparge>
		<temp units="C">80</temp>
		<time>20 min</time>
	  </sparge>
	  <preboil>
		<time>55 min</time>
	  </preboil>
	  <boil>
		<time>90 min</time>
	  </boil>
	  <chill>
		<time>43 min</time>
	  </chill>
	  <primary>
		<time>14 days</time>
	  </primary>
	</summary>
	<action>
	  <time>2:39</time>
	  <temp units="C">18</temp>
	  <desc>12L Dough in</desc>
	</action>
	<action>
	  <time>3:12</time>
	  <temp units="C">55</temp>
	  <desc>Heat off</desc>
	</action>
	<action>
	  <time>3:42</time>
	  <temp units="C">57</temp>
	  <desc>Heat on</desc>
	</action>
	<action>
	  <time>3:51</time>
	  <temp units="C">65</temp>
	  <desc>Heat off</desc>
	</action>
	<action>
	  <time>4:00</time>
	  <temp units="C">67</temp>
	  <desc>Turned on heat for 3 min to boost temp</desc>
	</action>
	<action>
	  <time>4:41</time>
	  <temp units="C">65</temp>
	  <desc>Heat on</desc>
	</action>
	<action>
	  <time>5:01</time>
	  <temp units="C">80</temp>
	  <desc>Heat off</desc>
	</action>
	<action>
	  <time>5:25</time>
	  <desc>Start Sparge -- recirculate 6L</desc>
	</action>
	<action>
	  <time>5:45</time>
	  <desc>End Sparge</desc>
	</action>
	<action>
	  <time>6:40</time>
	  <desc>Wort boiling</desc>
	</action>
	<action>
	  <time>7:09</time>
	  <desc>First addition of hops</desc>
	</action>
	<action>
	  <time>7:55</time>
	  <desc>Second addition of hops</desc>
	</action>
	<action>
	  <time>8:17</time>
	  <desc>Start Chill</desc>
	</action>
	<action>
	  <time>9:00</time>
	  <desc>Done!!!</desc>
	</action>
	<action>
	  <time>July 6</time>
	  <desc>Bottle with 2/3 cup dextrose</desc>
	</action>
  </log>
  <notes>
  <p>
  Supposedly a Boddington's clone.
  This one worked out OK.  At bottling time, I thought this would be
  one of the best beers I've ever made.  It was hoppy, crisp, with
  some nice apple esters.  When it was conditioned, it was merely OK.
  All the apple esters dissappeared.  To improve it, I'd add some more
  hops in the middle of the boil and use a different yeast.  In
  retrospect, I've come to dislike 1098.
  </p>
  </notes>
</beer>

=== mikekchar/brewfar/House.xml
<?xml version="1.0" standalone="no" ?>
<?xml-stylesheet type="text/xsl" href="brewfar1.xsl" ?>
<!DOCTYPE beer SYSTEM "beer.dtd">
<beer>
  <name>House Ale #1</name>
  <style>Brown Ale</style>
  <first-brewed>June 29, 2003</first-brewed>
  <brewers>Mike, Don, Nick, Suzanne</brewers>
  <ingredients>
	<fermentables>
	  <malt>
		<type>Crystal Malt</type>
		<qty units="g">372</qty>
		<added>mash</added>
	  </malt>
	  <malt>
		<type>Roast Barley</type>
		<qty units="g">78</qty>
		<added>mash</added>
	  </malt>
	  <malt>
		<type>2 Row Pale Ale</type>
		<qty units="kg">4.5</qty>
		<added>mash</added>
	  </malt>
	</fermentables>
	<flavourings>
	  <hop>
		<type>Perle</type>
		<acid>6.7</acid>
		<qty units="g">12</qty>
		<added>60</added>
	  </hop>
	  <hop>
		<type>Tettnanger</type>
		<acid>4.9</acid>
		<qty units="g">15</qty>
		<added>60</added>
	  </hop>
	  <hop>
		<type>Tettnanger</type>
		<acid>4.9</acid>
		<qty units="g">30</qty>
		<added>40</added>
	  </hop>
	  <hop>
		<type>Goldings</type>
		<acid>5.0</acid>
		<qty units="g">10</qty>
		<added>15</added>
	  </hop>
	</flavourings>
	<yeast>
	  <type>WYeast 1098 British Ale Yeast</type>
	  <qty units="Yeast Cake"></qty>
	  <added>Primary</added>
	</yeast>
	<priming>
	  <type>Dextrose</type>
	  <qty units="cup">Unknown (probably 0.5)</qty>
	</priming>
  </ingredients>
  <stats>
	<sg>46</sg>
	<fg>11</fg>
	<attenuation>76%</attenuation>
	<extract>75%</extract>
	<colour>25.8</colour>
	<ibu>31.6</ibu>
  </stats>
  <log>
	<summary>
	  <type>Step Controlled</type>
	  <mashin>
		<temp units="C">19</temp>
		<thickness units="l/kg">2.8</thickness>
	  </mashin>
	  <protein>
		<temp units="C">58</temp>
		<time>28 min</time>
	  </protein>
	  <sacharification>
		<temp units="C">64</temp>
		<time>58 min</time>
	  </sacharification>
	  <mashout>
		<temp units="C">80</temp>
		<time>15 min</time>
	  </mashout>
	  <sparge>
		<temp units="C">80</temp>
		<time>33 min</time>
	  </sparge>
	  <preboil>
		<time>49 min</time>
	  </preboil>
	  <boil>
		<time>90 min</time>
	  </boil>
	  <chill>
		<time>32 min</time>
	  </chill>
	  <primary>
		<time>14 days</time>
	  </primary>
	  <secondary>
		<time>7 days</time>
	  </secondary>
	</summary>
	<action>
	  <time>4:18</time>
	  <temp units="C">19</temp>
	  <desc>Dough in 14L</desc>
	</action>
	<action>
	  <time>4:56</time>
	  <temp units="C">58</temp>
	  <desc>Heat Off</desc>
	</action>
	<action>
	  <time>5:24</time>
	  <temp units="C">56</temp>
	  <desc>Heat On</desc>
	</action>
	<action>
	  <time>5:36</time>
	  <temp units="C">64</temp>
	  <desc>Heat Off</desc>
	</action>
	<action>
	  <time>6:34</time>
	  <temp units="C">63</temp>
	  <desc>Heat On</desc>
	</action>
	<action>
	  <time>7:01</time>
	  <temp units="C">80</temp>
	  <desc>Heat Off</desc>
	</action>
	<action>
	  <time>7:16</time>
	  <temp units="C">81</temp>
	  <desc>Sparge Start -- Recirculate 5.5L</desc>
	</action>
	<action>
	  <time>7:49</time>
	  <desc>End Sparge</desc>
	</action>
	<action>
	  <time>8:38</time>
	  <desc>Boil Starts</desc>
	</action>
	<action>
	  <time>9:08</time>
	  <desc>First addition of hops</desc>
	</action>
	<action>
	  <time>9:28</time>
	  <desc>Second addition of hops</desc>
	</action>
	<action>
	  <time>10:08</time>
	  <desc>Boil off</desc>
	</action>
	<action>
	  <time>10:40</time>
	  <temp units="C">20</temp>
	  <desc>Cooling finished</desc>
	</action>
	<action>
	  <time>July 13</time>
	  <desc>rack</desc>
	</action>
	<action>
	  <time>July 20</time>
	  <desc>bottle</desc>
	</action>
  </log>
  <notes>
  <p>
  This is not a bad little beer.  I'm drinking it now after 10 months
  and it's quite nice.  I can't believe it's 30+ IBUs, though.  And
  looking at the log, we didn't record one of the hop additions...
  Anyway, the colour is beautiful.  It's a dark reddish brown.  Just
  enough roastiness to make it nice.  Not quite to style since it
  should probably use chocolate, but I don't care.  The roast barley
  goes well with the german hops.  As you can probably tell, this
  was a "throw in what you've got" recipe.  However, we voted on the
  hops based on what we thought smelled nice.  Thus the strange hop
  schedule.  It's a bit muddy and I would get rid of the Goldings
  next time.  Also, I don't like the yeast.  I'd go with K97 next time.
  </p>
  </notes>
</beer>
